### ISSUE TITLE
Your component is featured in one of the Vaadin blog

### ISSUE THREAD

**Issue by binhbbbb** [MyScript/myscript-math-web#4]
Hi MyScript,

I am Binh Bui, the Community Marketing Specialist of Vaadin. First off, just want to say that you guys have developed a super awesome web component. We really like it, therefore we dedicated a whole blog to this component [A web component that lets you integrate mathematical expressions handwriting recognition](https://vaadin.com/blog/wcw-12-myscript-math-web).

Also feel free to leave a comment under the comment section or this tweet [here](https://twitter.com/binhbbbb/status/999238825430921217).

Cheers!

**Comment by padewitte** [comment]
Thanks a lot
