### ISSUE TITLE
about the math recognition

### ISSUE THREAD

**Issue by af258963** [MyScript/myscript-math-web#6]
Thanks for sharing! Does the math formula recognition code which you used  is open source? Or where is the formula recognition algorithm interface you have called? Thanks.

**Comment by padewitte** [comment]
The code for recognition of the handwriting is close source. All the recognition process is hod by MyScript Servers.

You can find more details on our [documentation](https://developer.myscript.com/docs/interactive-ink/1.2/overview/about/)

**Comment by af258963** [comment]
@padewitte thank you for reply.
